import Link from "next/link";
import { Ticket, ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Discount Redemption Terms | LivingGo",
};

const sections = [
  {
    title: "1. Purpose and Parties",
    content: `These Student Discount and Referral Code Redemption Terms ("Terms") govern the availing of a Discount by a Student through a Coupon Code generated by a Partner under LivingGo's Partner Coupon Creation and Payout Agreement. These Terms apply between RCT Accommodations and Infrastructure Private Limited, CIN U68100BR2026PTC084883, having its registered office at BE.NO.005.1012, Shivpuri Colony, Bettiah, West Champaran – 845438, Bihar, India, operating under the brand name "LivingGo" ("LivingGo", "Company", "Platform") AND any Student applying or attempting to apply a Coupon Code through the Platform ("Student", "User").`,
  },
  {
    title: "2. Definitions",
    content: `"Coupon Code" or "Referral Code" means a code generated by a Partner and approved by LivingGo, entitling an eligible Student to a Discount on redemption. "Discount" means the reduction in booking-related charges specified against a given Coupon Code. "Eligible Booking" means a booking that satisfies the eligibility, timing and verification conditions set out in these Terms. "Booking Token" means the amount payable by a Student to confirm a booking on the Platform, against which a Discount may be applied. "Partner" means the Student, Creator or Affiliate who generated the Coupon Code.`,
  },
  {
    title: "3. Eligibility to Redeem",
    content: `A Student must satisfy the eligibility conditions specified against the particular Coupon Code (for example, first-time booking, specific property, city, or course of study), where such conditions are displayed. Only one Coupon Code may be applied per booking, unless the Platform expressly permits combination for a specific campaign. A Coupon Code must be entered at the stage and through the interface specified on the Platform. Coupon Codes shall not be applied retroactively to a booking already confirmed, except where LivingGo expressly permits this in writing.`,
  },
  {
    title: "4. How and When the Discount Becomes Available",
    content: `The Student enters the Coupon Code at the applicable checkout or Booking Token stage. The Platform validates the Coupon Code for activity, expiry, usage cap and Student eligibility before applying the Discount. Where valid, the Discount is reflected as a reduction against the Booking Token or, where specified for that Coupon Code, against the first month's rent or another designated charge. The Discount displayed at checkout is provisional until the underlying booking is confirmed and, where applicable, occupancy or verification conditions specified for that Coupon Code are satisfied. LivingGo may reverse a provisionally applied Discount if the booking is not completed, is cancelled, or is later found ineligible.`,
  },
  {
    title: "5. Validity and Expiry",
    content: `Each Coupon Code carries a validity window and/or usage cap determined by LivingGo. A Coupon Code that has expired or reached its usage cap shall not be honoured, notwithstanding any earlier on-screen display, save where such display resulted from a demonstrable LivingGo system error.`,
  },
  {
    title: "6. Discount Value and Type",
    content: `A Discount may be a percentage or a flat amount, and may be subject to a maximum cap, as specified at the time the Coupon Code is displayed to the Student. LivingGo may designate specific properties, room categories, or cities as excluded from a given Coupon Code.`,
  },
  {
    title: "7. Stacking and Exclusivity",
    content: `Unless expressly stated otherwise for a specific campaign, a Coupon Code cannot be combined with any other coupon code, promotional offer, or discount. Where a Student attempts to apply more than one Coupon Code to the same booking, LivingGo may apply whichever is more beneficial to the Student, or may hold the booking for manual review, at its discretion.`,
  },
  {
    title: "8. Student Benefits",
    content: `A Student who successfully redeems a valid Coupon Code receives the Discount specified against that code, applied to the Booking Token or designated charge. A Student is not required to pay any fee to the Partner, or to LivingGo, in exchange for using a Coupon Code. Redemption of a Coupon Code does not create any contractual relationship between the Student and the Partner. LivingGo remains the sole contracting party in respect of the underlying booking.`,
  },
  {
    title: "9. Non-Transferability",
    content: `A Coupon Code is issued for use in connection with the specific Partner campaign or referral relationship for which it was generated, and may not be resold, published for unauthorised mass use, or transferred for consideration.`,
  },
  {
    title: "10. Restrictions and Disqualification",
    content: `LivingGo may withdraw or reverse a Discount, at any stage, where: the Student is subsequently found ineligible for the applicable Coupon Code; the underlying booking is cancelled, reversed, or found to be fraudulent; collusion between the Student and the Partner, or misuse of the Coupon Code, is reasonably suspected; multiple accounts are used to redeem the same Coupon Code beyond its permitted usage. Subject to genuine and demonstrable error, LivingGo's determination as to the validity of a redemption shall be final.`,
  },
  {
    title: "11. Effect of Cancellation or Refund",
    content: `Where an Eligible Booking on which a Discount was applied is subsequently cancelled or refunded, LivingGo may reverse the Discount. Depending on the stage of the booking, the Student may become liable for the difference between the discounted and undiscounted charge, and any corresponding Partner Payout may be adjusted or clawed back.`,
  },
  {
    title: "12. LivingGo's Right to Modify or Withdraw",
    content: `LivingGo may modify, suspend, or withdraw any Coupon Code, referral campaign, or these Terms at any time, with or without prior notice, including after a Coupon Code has been publicised or shared. Such modification or withdrawal shall not affect a Discount already confirmed on a completed Eligible Booking.`,
  },
  {
    title: "13. Use of Student Data",
    content: `Information provided by the Student in connection with redemption of a Coupon Code — including identity, contact details, booking information, and the Coupon Code used — shall be processed in accordance with LivingGo's Privacy Policy, including for the purposes of fraud verification and reconciliation of the associated Partner Payout.`,
  },
  {
    title: "14. Disclaimer",
    content: `Discounts are made available at LivingGo's discretion as part of its promotional and referral initiatives. A Coupon Code does not constitute a standalone contractual entitlement independent of an Eligible Booking, and availability of any particular Coupon Code, campaign, or Discount value is not guaranteed.`,
  },
  {
    title: "15. Grievance Redressal",
    content: `For concerns relating to a Discount or Coupon Code redemption, the Student may contact: Grievance Officer, RCT Accommodations and Infrastructure Private Limited, Email: privacy@livinggo.in`,
  },
  {
    title: "16. Governing Law and Arbitration",
    content: `Governing Law: Laws of India. Seat of Arbitration: Delhi. Language: English. Parties shall first attempt amicable resolution; if unresolved within thirty (30) days, disputes shall be referred to arbitration under the Arbitration and Conciliation Act, 1996.`,
  },
  {
    title: "17. Electronic Acceptance",
    content: `Application of a Coupon Code by the Student during the booking process, together with any OTP verification, click-wrap acceptance, or dashboard confirmation, shall constitute legally binding acceptance of these Terms.`,
  },
];

export default function StudentDiscountTermsPage() {
  return (
    <main className="min-h-screen bg-linen px-4 py-10 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-ink"
        >
          <ArrowLeft className="h-4 w-4" aria-hidden />
          Back to home
        </Link>
        <div className="rounded-3xl bg-white p-6 shadow-soft sm:p-10">
          <div className="mb-8 flex items-start gap-4">
            <div className="rounded-2xl bg-linen p-3">
              <Ticket className="h-7 w-7 text-clay" aria-hidden />
            </div>
            <div>
              <p className="text-sm font-black uppercase text-clay">LivingGo Legal</p>
              <h1 className="mt-1 text-3xl font-black text-ink sm:text-4xl">
                Student Discount Redemption Terms
              </h1>
              <p className="mt-2 text-sm text-muted">
                RCT Accommodations and Infrastructure Private Limited — operating as LivingGo
              </p>
            </div>
          </div>
          <div className="space-y-6">
            {sections.map((section) => (
              <div key={section.title} className="rounded-2xl bg-linen p-5">
                <h2 className="mb-2 text-sm font-black text-ink">{section.title}</h2>
                <p className="text-sm leading-7 text-muted">{section.content}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 rounded-2xl border border-black/10 p-4 text-center text-xs text-muted">
            By applying a coupon code during booking on the LivingGo platform, you acknowledge having read and accepted these Student Discount Redemption Terms.
          </div>
        </div>
      </div>
    </main>
  );
}